#!/bin/sh

# Copyright (c) 2018-2025, Firas Khalil Khana
# Distributed under the terms of the ISC License

exec meson setup \
  --prefix=/usr \
  --libexecdir=lib \
  --sbindir=bin \
  --buildtype=release \
  --default-library=shared \
  --stdsplit \
  --strip \
  --wrap-mode=nodownload \
  -Db_lto=true \
  -Db_lto_mode=thin \
  -Db_pie=true \
  --cross-file meson.cross.$XARCH \
  "$@"
