#!/bin/sh

# Copyright © 2018-2025 Firas Khana
# Distributed under the terms of the ISC License

exec meson setup \
  -Dprefix=/usr \
  -Dlibexecdir=lib \
  -Dsbindir=bin \
  -Dbuildtype=release \
  -Ddefault_library=shared \
  -Dstdsplit=true \
  -Dstrip=true \
  -Dwrap_mode=nodownload \
  -Db_lto=true \
  -Db_lto_mode=thin \
  -Db_pie=true \
  --cross-file meson.cross.$XARCH \
  "$@"
